# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/main.go

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

furies:
  - account: shamilovstas

nfpms:
  - id: motd-joke
    package_name: motd-joke
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Stanislav Shamilov <shamilovstas@protonmail.com>
    description: |-
      motd-joke installer package.
      Set top of the day joke from r/Jokes as MOTD
    license: Apache 2.0

    formats:
      - apk
      - deb
      - rpm
      - archlinux

    dependencies:
      - systemd

    bindir: /usr/local/bin

    # Section.
    section: main

    contents:
      # Basic file that applies to all packagers
      - src: init/systemd/motd-joke.service
        dst: /etc/systemd/system/motd-joke.service

      - src: init/systemd/motd-joke.timer
        dst: /etc/systemd/system/motd-joke.timer

      - src: templates/debian-motd-joke.tpl
        dst: /usr/share/motd-joke/debian-motd-joke.tpl
        packager: deb